name: Deploying to Production

on:
  push:
    branches:
      - master

jobs:
  testing-first: 
    runs-on: ubuntu-18.04
    steps: 
      - name: Deploying to Production
        run: echo "Deploying to Production"

      - name: Deploying date
        run: date
      - run: cd /home/runner/work/logs_registry/logs_registry && ls -l
